---
Description: CodePipeline notifications.
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  queue:
    Description: Nome da Queue
    Type: String
    Default: codemetrics

  TableName:
    Description: Nome da table do DynamoDB
    Type: String
    Default: codemetrics
  

Resources:
  RoleSQSCodeMetrics:
       Type: AWS::IAM::Role
       Properties:
         AssumeRolePolicyDocument:
           Version: '2012-10-17'
           Statement:
           - Effect: Allow
             Principal:
               Service:
               - events.amazonaws.com
               - sqs.amazonaws.com
             Action:
             - sts:AssumeRole
         Path: "/"
         Policies:
         - PolicyName: SqsCodeMetricsRole
           PolicyDocument:
             Version: '2012-10-17'
             Statement:
             - Effect: Allow
               Action:
               - sqs:*
               Resource: !GetAtt SQSCodeMetricsQueue.Arn

  EventRuleStages: 
    Type: "AWS::Events::Rule"
    Properties:
      Name: !Sub ${TableName}-Rules-Pipeline 
      Description: "EventRule"
      EventPattern: 
        source:
        - aws.codepipeline
      State: "ENABLED"
      RoleArn: !GetAtt RoleSQSCodeMetrics.Arn
      Targets: 
        - 
          Arn: !GetAtt SQSCodeMetricsQueue.Arn
          Id:  !Ref queue


  SQSCodeMetricsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref queue
      MessageRetentionPeriod: 864000

  CodeMetricsQueuePolicy:      
    Type: AWS::SQS::QueuePolicy
    Properties: 
      PolicyDocument:
        Version: 2012-10-17
        Id: MyQueuePolicy
        Statement: 
         - Effect: Allow
           Principal: 
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com                       
           Action: ['sqs:SendMessage']
           Resource: !GetAtt SQSCodeMetricsQueue.Arn
      Queues: [!Ref 'SQSCodeMetricsQueue']

  DyPipelines:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TableName}-pipelines
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: running
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: running
          KeyType: RANGE  
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DyMetricas:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TableName}-metricas
      AttributeDefinitions:
        - AttributeName: account
          AttributeType: S
        - AttributeName: resource_id
          AttributeType: S
      KeySchema:
        - AttributeName: account
          KeyType: HASH
        - AttributeName: resource_id
          KeyType: RANGE  

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DyRaw:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TableName}-raw
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1