def pipeline_success(account,execution_id,pipeline,region, pipeline_id):
    
    tmp = "arn:aws:codepipeline:{0}:{1}:{2}".format(region, account,pipeline)
    arn =[tmp]
    chamada_api = []
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region":region, "state": "STARTED", "version": 2.0, "action": "Compilacao", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:25Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "STARTED", "stage": "CI"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:24Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "TestUnit", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:51:27Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "SUCCEEDED", "stage": "SourceCode"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:24Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "Compilacao", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:51:28Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "STARTED", "stage": "Publish"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:52:32Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "Source", "type": {"owner": "AWS", "category": "Source", "version": "1", "provider": "CodeCommit"}, "stage": "SourceCode"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:23Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "STARTED"}, "detail-type": "CodePipeline Pipeline Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:17Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "Scan", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:52:32Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "STARTED", "stage": "SourceCode"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:17Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "STARTED", "version": 2.0, "action": "TestUnit", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:24Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "SUCCEEDED", "stage": "Publish"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:53:36Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "SUCCEEDED"}, "detail-type": "CodePipeline Pipeline Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:53:36Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"eventVersion": "1.05", "eventID": "28f9c968-9ab7-49b1-ab53-f23d8ca9c986", "eventTime": "2019-07-30T20:50:17Z", "requestParameters": {"name": pipeline, "clientRequestToken": "27da5ffc-79fe-4387-b55c-0e0fbbe108d5"}, "eventType": "AwsApiCall", "responseElements": {"pipelineExecutionId": execution_id}, "awsRegion": region, "eventName": "StartPipelineExecution", "userIdentity": {"userName": "jose@localhost", "principalId": "123123123", "accessKeyId": "324234324", "invokedBy": "signin.amazonaws.com", "sessionContext": {"attributes": {"creationDate": "2019-07-30T20:42:54Z", "mfaAuthenticated": "false"}}, "type": "IAMUser", "arn": "arn:aws:iam::325847872862:user/clodonil.trigo@itau-unibanco.com.br", "accountId": account}, "eventSource": "codepipeline.amazonaws.com", "requestID": "b72b78a0-dacd-4def-a963-79fe6fdc3e8f", "userAgent": "signin.amazonaws.com", "sourceIPAddress": "200.196.153.14"}, "detail-type": "AWS API Call via CloudTrail", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:17Z", "id": "f591323b-3cfd-4dc4-6efc-37903edf77ec", "resources": []})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "ECR", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "Publish"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:53:36Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "STARTED", "version": 2.0, "action": "Scan", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:51:29Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "STARTED", "version": 2.0, "action": "ECR", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "Publish"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:52:33Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "STARTED", "version": 2.0, "action": "Source", "type": {"owner": "AWS", "category": "Source", "version": "1", "provider": "CodeCommit"}, "stage": "SourceCode"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:18Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "SUCCEEDED", "stage": "CI"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:52:32Z", "id": pipeline_id, "resources": arn})

    return chamada_api

def pipeline_faild(account,execution_id,pipeline,region, pipeline_id):

    tmp = "arn:aws:codepipeline:{0}:{1}:{2}".format(region, account,pipeline)
    arn =[tmp]
    chamada_api = []
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region":region, "state": "STARTED", "version": 2.0, "action": "Compilacao", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:25Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "STARTED", "stage": "CI"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:24Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "TestUnit", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:51:27Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "SUCCEEDED", "stage": "SourceCode"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:24Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "Compilacao", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:51:28Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "STARTED", "stage": "Publish"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:52:32Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "Source", "type": {"owner": "AWS", "category": "Source", "version": "1", "provider": "CodeCommit"}, "stage": "SourceCode"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:23Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "STARTED"}, "detail-type": "CodePipeline Pipeline Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:17Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "SUCCEEDED", "version": 2.0, "action": "Scan", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:52:32Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "STARTED", "stage": "SourceCode"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:17Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "STARTED", "version": 2.0, "action": "TestUnit", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:24Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "FAILED", "stage": "Publish"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:53:36Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "FAILED"}, "detail-type": "CodePipeline Pipeline Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:53:36Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"eventVersion": "1.05", "eventID": "28f9c968-9ab7-49b1-ab53-f23d8ca9c986", "eventTime": "2019-07-30T20:50:17Z", "requestParameters": {"name": pipeline, "clientRequestToken": "27da5ffc-79fe-4387-b55c-0e0fbbe108d5"}, "eventType": "AwsApiCall", "responseElements": {"pipelineExecutionId": execution_id}, "awsRegion": region, "eventName": "StartPipelineExecution", "userIdentity": {"userName": "jose@localhost", "principalId": "123123123", "accessKeyId": "324234324", "invokedBy": "signin.amazonaws.com", "sessionContext": {"attributes": {"creationDate": "2019-07-30T20:42:54Z", "mfaAuthenticated": "false"}}, "type": "IAMUser", "arn": "arn:aws:iam::325847872862:user/clodonil.trigo@itau-unibanco.com.br", "accountId": account}, "eventSource": "codepipeline.amazonaws.com", "requestID": "b72b78a0-dacd-4def-a963-79fe6fdc3e8f", "userAgent": "signin.amazonaws.com", "sourceIPAddress": "200.196.153.14"}, "detail-type": "AWS API Call via CloudTrail", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:17Z", "id": "f591323b-3cfd-4dc4-6efc-37903edf77ec", "resources": []})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "FAILED", "version": 2.0, "action": "ECR", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "Publish"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:53:36Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "STARTED", "version": 2.0, "action": "Scan", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "CI"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:51:29Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "STARTED", "version": 2.0, "action": "ECR", "type": {"owner": "AWS", "category": "Build", "version": "1", "provider": "CodeBuild"}, "stage": "Publish"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:52:33Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "region": region, "state": "STARTED", "version": 2.0, "action": "Source", "type": {"owner": "AWS", "category": "Source", "version": "1", "provider": "CodeCommit"}, "stage": "SourceCode"}, "detail-type": "CodePipeline Action Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:50:18Z", "id": pipeline_id, "resources": arn})
    chamada_api.append({"account": account, "region": region, "detail": {"execution-id": execution_id, "pipeline": pipeline, "version": 2.0, "state": "SUCCEEDED", "stage": "CI"}, "detail-type": "CodePipeline Stage Execution State Change", "source": "aws.codepipeline", "version": "0", "time": "2019-07-30T20:52:32Z", "id": pipeline_id, "resources": arn})

    return chamada_api
