version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - grafana
      
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000


#  code-metrics:
#    build: ../code-metrics-api/.
#    ports:
#       - 8080:8080


