version: '3'
services:
  prometheus:
    image: clodonil/prometheus:latest
    environment:
    - API_URL=codemetrics-api:8080
    ports:
      - 9090:9090
    links:
      - codemetrics-api    
  
  grafana:
    image: clodonil/grafana:latest
    depends_on:
      - prometheus  
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAPASS}
      - GF_USERS_ALLOW_SIGN_UP=false
    links:
      - prometheus
  
  codemetrics-api:
    image: clodonil/codemetrics-api:latest
    environment:
       - AWS_ACCESS_ID=${AWS_ACCESS_ID}
       - AWS_SECRET_KEY=${AWS_SECRET_KEY}
       - DYNAMODB_TABLE=pipelines
    ports:
       - 8080:8080

