version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
      
  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus  
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=redepp
      - GF_USERS_ALLOW_SIGN_UP=false

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000


  code-metrics-api:
    container_name: code-metrics-api
    build: ../code-metrics-api/.
    ports:
       - 8080:8080
    depends_on:
      - dynamodb 
    links:
      - prometheus
      - dynamodb 


